// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_autores.proto

package com.autores.protos;

public interface AddressAutoresOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressAutores)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Autor autor = 1;</code>
   */
  java.util.List<com.autores.protos.Autor> 
      getAutorList();
  /**
   * <code>repeated .tutorial.Autor autor = 1;</code>
   */
  com.autores.protos.Autor getAutor(int index);
  /**
   * <code>repeated .tutorial.Autor autor = 1;</code>
   */
  int getAutorCount();
  /**
   * <code>repeated .tutorial.Autor autor = 1;</code>
   */
  java.util.List<? extends com.autores.protos.AutorOrBuilder> 
      getAutorOrBuilderList();
  /**
   * <code>repeated .tutorial.Autor autor = 1;</code>
   */
  com.autores.protos.AutorOrBuilder getAutorOrBuilder(
      int index);
}
