// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mensagem.proto

package com.mensagem.protos;

public interface AddressMensagemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressMensagem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Mensagem mensagem = 1;</code>
   */
  java.util.List<com.mensagem.protos.Mensagem> 
      getMensagemList();
  /**
   * <code>repeated .tutorial.Mensagem mensagem = 1;</code>
   */
  com.mensagem.protos.Mensagem getMensagem(int index);
  /**
   * <code>repeated .tutorial.Mensagem mensagem = 1;</code>
   */
  int getMensagemCount();
  /**
   * <code>repeated .tutorial.Mensagem mensagem = 1;</code>
   */
  java.util.List<? extends com.mensagem.protos.MensagemOrBuilder> 
      getMensagemOrBuilderList();
  /**
   * <code>repeated .tutorial.Mensagem mensagem = 1;</code>
   */
  com.mensagem.protos.MensagemOrBuilder getMensagemOrBuilder(
      int index);
}
