// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mensagem.proto

package com.mensagem.protos;

public interface MensagemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Mensagem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messageType = 1;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>int32 request_id = 2;</code>
   * @return The requestId.
   */
  int getRequestId();

  /**
   * <code>string object_reference = 3;</code>
   * @return The objectReference.
   */
  java.lang.String getObjectReference();
  /**
   * <code>string object_reference = 3;</code>
   * @return The bytes for objectReference.
   */
  com.google.protobuf.ByteString
      getObjectReferenceBytes();

  /**
   * <code>string method = 4;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 4;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>bytes arguments = 5;</code>
   * @return The arguments.
   */
  com.google.protobuf.ByteString getArguments();

  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
