// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Autores.proto

package com.autores.protos;

public final class AddressAutoresProtos {
  private AddressAutoresProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Autor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Autor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressAutores_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_AddressAutores_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAutores.proto\022\010tutorial\032\037google/protob" +
      "uf/timestamp.proto\"o\n\005Autor\022\014\n\004name\030\001 \001(" +
      "\t\022\n\n\002id\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\013\n\003cpf\030\004 \001(" +
      "\t\0220\n\014last_updated\030\005 \001(\0132\032.google.protobu" +
      "f.Timestamp\"0\n\016AddressAutores\022\036\n\005autor\030\001" +
      " \003(\0132\017.tutorial.AutorBb\n\022com.autores.pro" +
      "tosB\024AddressAutoresProtosP\001Z\n../autores\252" +
      "\002\'Google.Protobuf.Examples.AddressAutore" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_Autor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Autor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Autor_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Cpf", "LastUpdated", });
    internal_static_tutorial_AddressAutores_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_AddressAutores_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_AddressAutores_descriptor,
        new java.lang.String[] { "Autor", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
