// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emprestimo.proto

package com.emprestimos.protos;

public final class AddressEmprestimosProtos {
  private AddressEmprestimosProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Emprestimo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Emprestimo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressEmprestimos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_AddressEmprestimos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Emprestimo.proto\022\010tutorial\032\037google/pro" +
      "tobuf/timestamp.proto\"\204\001\n\nEmprestimo\022\016\n\006" +
      "codigo\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\023\n\013dataReserva\030" +
      "\003 \001(\t\022\023\n\013dataEntrega\030\004 \001(\t\0220\n\014last_updat" +
      "ed\030\005 \001(\0132\032.google.protobuf.Timestamp\">\n\022" +
      "AddressEmprestimos\022(\n\nemprestimo\030\001 \003(\0132\024" +
      ".tutorial.EmprestimoBr\n\026com.emprestimos." +
      "protosB\030AddressEmprestimosProtosP\001Z\016../e" +
      "mprestimos\252\002+Google.Protobuf.Examples.Ad" +
      "dressEmprestimosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_Emprestimo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Emprestimo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Emprestimo_descriptor,
        new java.lang.String[] { "Codigo", "Id", "DataReserva", "DataEntrega", "LastUpdated", });
    internal_static_tutorial_AddressEmprestimos_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_AddressEmprestimos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_AddressEmprestimos_descriptor,
        new java.lang.String[] { "Emprestimo", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
