// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emprestimo.proto

package com.emprestimos.protos;

public final class AddressEmprestimosProtos {
  private AddressEmprestimosProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Emprestimo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Emprestimo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressEmprestimos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_AddressEmprestimos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Emprestimo.proto\022\010tutorial\032\037google/pro" +
      "tobuf/timestamp.proto\"\230\001\n\nEmprestimo\022\n\n\002" +
      "id\030\001 \001(\t\022\016\n\006codigo\030\002 \001(\t\022\022\n\nquantidade\030\003" +
      " \001(\t\022\023\n\013dataReserva\030\004 \001(\t\022\023\n\013dataEntrega" +
      "\030\005 \001(\t\0220\n\014last_updated\030\006 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\">\n\022AddressEmprestimos\022(" +
      "\n\nemprestimo\030\001 \003(\0132\024.tutorial.Emprestimo" +
      "Br\n\026com.emprestimos.protosB\030AddressEmpre" +
      "stimosProtosP\001Z\016../emprestimos\252\002+Google." +
      "Protobuf.Examples.AddressEmprestimosb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_Emprestimo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Emprestimo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Emprestimo_descriptor,
        new java.lang.String[] { "Id", "Codigo", "Quantidade", "DataReserva", "DataEntrega", "LastUpdated", });
    internal_static_tutorial_AddressEmprestimos_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_AddressEmprestimos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_AddressEmprestimos_descriptor,
        new java.lang.String[] { "Emprestimo", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
