// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emprestimo.proto

package com.emprestimos.protos;

public interface AddressEmprestimosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressEmprestimos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  java.util.List<com.emprestimos.protos.Emprestimo> 
      getEmprestimoList();
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  com.emprestimos.protos.Emprestimo getEmprestimo(int index);
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  int getEmprestimoCount();
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  java.util.List<? extends com.emprestimos.protos.EmprestimoOrBuilder> 
      getEmprestimoOrBuilderList();
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  com.emprestimos.protos.EmprestimoOrBuilder getEmprestimoOrBuilder(
      int index);
}
