// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emprestimo.proto

package com.emprestimos.protos;

/**
 * <pre>
 * Our address book file is just one of these.
 * </pre>
 *
 * Protobuf type {@code tutorial.AddressEmprestimos}
 */
public final class AddressEmprestimos extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.AddressEmprestimos)
    AddressEmprestimosOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddressEmprestimos.newBuilder() to construct.
  private AddressEmprestimos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddressEmprestimos() {
    emprestimo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddressEmprestimos();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddressEmprestimos(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              emprestimo_ = new java.util.ArrayList<com.emprestimos.protos.Emprestimo>();
              mutable_bitField0_ |= 0x00000001;
            }
            emprestimo_.add(
                input.readMessage(com.emprestimos.protos.Emprestimo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        emprestimo_ = java.util.Collections.unmodifiableList(emprestimo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_AddressEmprestimos_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_AddressEmprestimos_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emprestimos.protos.AddressEmprestimos.class, com.emprestimos.protos.AddressEmprestimos.Builder.class);
  }

  public static final int EMPRESTIMO_FIELD_NUMBER = 1;
  private java.util.List<com.emprestimos.protos.Emprestimo> emprestimo_;
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.emprestimos.protos.Emprestimo> getEmprestimoList() {
    return emprestimo_;
  }
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.emprestimos.protos.EmprestimoOrBuilder> 
      getEmprestimoOrBuilderList() {
    return emprestimo_;
  }
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  @java.lang.Override
  public int getEmprestimoCount() {
    return emprestimo_.size();
  }
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  @java.lang.Override
  public com.emprestimos.protos.Emprestimo getEmprestimo(int index) {
    return emprestimo_.get(index);
  }
  /**
   * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
   */
  @java.lang.Override
  public com.emprestimos.protos.EmprestimoOrBuilder getEmprestimoOrBuilder(
      int index) {
    return emprestimo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < emprestimo_.size(); i++) {
      output.writeMessage(1, emprestimo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < emprestimo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, emprestimo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emprestimos.protos.AddressEmprestimos)) {
      return super.equals(obj);
    }
    com.emprestimos.protos.AddressEmprestimos other = (com.emprestimos.protos.AddressEmprestimos) obj;

    if (!getEmprestimoList()
        .equals(other.getEmprestimoList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmprestimoCount() > 0) {
      hash = (37 * hash) + EMPRESTIMO_FIELD_NUMBER;
      hash = (53 * hash) + getEmprestimoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emprestimos.protos.AddressEmprestimos parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emprestimos.protos.AddressEmprestimos prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Our address book file is just one of these.
   * </pre>
   *
   * Protobuf type {@code tutorial.AddressEmprestimos}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.AddressEmprestimos)
      com.emprestimos.protos.AddressEmprestimosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_AddressEmprestimos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_AddressEmprestimos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emprestimos.protos.AddressEmprestimos.class, com.emprestimos.protos.AddressEmprestimos.Builder.class);
    }

    // Construct using com.emprestimos.protos.AddressEmprestimos.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmprestimoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (emprestimoBuilder_ == null) {
        emprestimo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        emprestimoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_AddressEmprestimos_descriptor;
    }

    @java.lang.Override
    public com.emprestimos.protos.AddressEmprestimos getDefaultInstanceForType() {
      return com.emprestimos.protos.AddressEmprestimos.getDefaultInstance();
    }

    @java.lang.Override
    public com.emprestimos.protos.AddressEmprestimos build() {
      com.emprestimos.protos.AddressEmprestimos result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emprestimos.protos.AddressEmprestimos buildPartial() {
      com.emprestimos.protos.AddressEmprestimos result = new com.emprestimos.protos.AddressEmprestimos(this);
      int from_bitField0_ = bitField0_;
      if (emprestimoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          emprestimo_ = java.util.Collections.unmodifiableList(emprestimo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.emprestimo_ = emprestimo_;
      } else {
        result.emprestimo_ = emprestimoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emprestimos.protos.AddressEmprestimos) {
        return mergeFrom((com.emprestimos.protos.AddressEmprestimos)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emprestimos.protos.AddressEmprestimos other) {
      if (other == com.emprestimos.protos.AddressEmprestimos.getDefaultInstance()) return this;
      if (emprestimoBuilder_ == null) {
        if (!other.emprestimo_.isEmpty()) {
          if (emprestimo_.isEmpty()) {
            emprestimo_ = other.emprestimo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmprestimoIsMutable();
            emprestimo_.addAll(other.emprestimo_);
          }
          onChanged();
        }
      } else {
        if (!other.emprestimo_.isEmpty()) {
          if (emprestimoBuilder_.isEmpty()) {
            emprestimoBuilder_.dispose();
            emprestimoBuilder_ = null;
            emprestimo_ = other.emprestimo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            emprestimoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmprestimoFieldBuilder() : null;
          } else {
            emprestimoBuilder_.addAllMessages(other.emprestimo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emprestimos.protos.AddressEmprestimos parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emprestimos.protos.AddressEmprestimos) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.emprestimos.protos.Emprestimo> emprestimo_ =
      java.util.Collections.emptyList();
    private void ensureEmprestimoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        emprestimo_ = new java.util.ArrayList<com.emprestimos.protos.Emprestimo>(emprestimo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emprestimos.protos.Emprestimo, com.emprestimos.protos.Emprestimo.Builder, com.emprestimos.protos.EmprestimoOrBuilder> emprestimoBuilder_;

    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public java.util.List<com.emprestimos.protos.Emprestimo> getEmprestimoList() {
      if (emprestimoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(emprestimo_);
      } else {
        return emprestimoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public int getEmprestimoCount() {
      if (emprestimoBuilder_ == null) {
        return emprestimo_.size();
      } else {
        return emprestimoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public com.emprestimos.protos.Emprestimo getEmprestimo(int index) {
      if (emprestimoBuilder_ == null) {
        return emprestimo_.get(index);
      } else {
        return emprestimoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder setEmprestimo(
        int index, com.emprestimos.protos.Emprestimo value) {
      if (emprestimoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmprestimoIsMutable();
        emprestimo_.set(index, value);
        onChanged();
      } else {
        emprestimoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder setEmprestimo(
        int index, com.emprestimos.protos.Emprestimo.Builder builderForValue) {
      if (emprestimoBuilder_ == null) {
        ensureEmprestimoIsMutable();
        emprestimo_.set(index, builderForValue.build());
        onChanged();
      } else {
        emprestimoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder addEmprestimo(com.emprestimos.protos.Emprestimo value) {
      if (emprestimoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmprestimoIsMutable();
        emprestimo_.add(value);
        onChanged();
      } else {
        emprestimoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder addEmprestimo(
        int index, com.emprestimos.protos.Emprestimo value) {
      if (emprestimoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmprestimoIsMutable();
        emprestimo_.add(index, value);
        onChanged();
      } else {
        emprestimoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder addEmprestimo(
        com.emprestimos.protos.Emprestimo.Builder builderForValue) {
      if (emprestimoBuilder_ == null) {
        ensureEmprestimoIsMutable();
        emprestimo_.add(builderForValue.build());
        onChanged();
      } else {
        emprestimoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder addEmprestimo(
        int index, com.emprestimos.protos.Emprestimo.Builder builderForValue) {
      if (emprestimoBuilder_ == null) {
        ensureEmprestimoIsMutable();
        emprestimo_.add(index, builderForValue.build());
        onChanged();
      } else {
        emprestimoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder addAllEmprestimo(
        java.lang.Iterable<? extends com.emprestimos.protos.Emprestimo> values) {
      if (emprestimoBuilder_ == null) {
        ensureEmprestimoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emprestimo_);
        onChanged();
      } else {
        emprestimoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder clearEmprestimo() {
      if (emprestimoBuilder_ == null) {
        emprestimo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        emprestimoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public Builder removeEmprestimo(int index) {
      if (emprestimoBuilder_ == null) {
        ensureEmprestimoIsMutable();
        emprestimo_.remove(index);
        onChanged();
      } else {
        emprestimoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public com.emprestimos.protos.Emprestimo.Builder getEmprestimoBuilder(
        int index) {
      return getEmprestimoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public com.emprestimos.protos.EmprestimoOrBuilder getEmprestimoOrBuilder(
        int index) {
      if (emprestimoBuilder_ == null) {
        return emprestimo_.get(index);  } else {
        return emprestimoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public java.util.List<? extends com.emprestimos.protos.EmprestimoOrBuilder> 
         getEmprestimoOrBuilderList() {
      if (emprestimoBuilder_ != null) {
        return emprestimoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(emprestimo_);
      }
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public com.emprestimos.protos.Emprestimo.Builder addEmprestimoBuilder() {
      return getEmprestimoFieldBuilder().addBuilder(
          com.emprestimos.protos.Emprestimo.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public com.emprestimos.protos.Emprestimo.Builder addEmprestimoBuilder(
        int index) {
      return getEmprestimoFieldBuilder().addBuilder(
          index, com.emprestimos.protos.Emprestimo.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.Emprestimo emprestimo = 1;</code>
     */
    public java.util.List<com.emprestimos.protos.Emprestimo.Builder> 
         getEmprestimoBuilderList() {
      return getEmprestimoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.emprestimos.protos.Emprestimo, com.emprestimos.protos.Emprestimo.Builder, com.emprestimos.protos.EmprestimoOrBuilder> 
        getEmprestimoFieldBuilder() {
      if (emprestimoBuilder_ == null) {
        emprestimoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.emprestimos.protos.Emprestimo, com.emprestimos.protos.Emprestimo.Builder, com.emprestimos.protos.EmprestimoOrBuilder>(
                emprestimo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        emprestimo_ = null;
      }
      return emprestimoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.AddressEmprestimos)
  }

  // @@protoc_insertion_point(class_scope:tutorial.AddressEmprestimos)
  private static final com.emprestimos.protos.AddressEmprestimos DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emprestimos.protos.AddressEmprestimos();
  }

  public static com.emprestimos.protos.AddressEmprestimos getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddressEmprestimos>
      PARSER = new com.google.protobuf.AbstractParser<AddressEmprestimos>() {
    @java.lang.Override
    public AddressEmprestimos parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddressEmprestimos(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddressEmprestimos> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddressEmprestimos> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emprestimos.protos.AddressEmprestimos getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

