// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Emprestimo.proto

package com.emprestimos.protos;

/**
 * <pre>
 * [START messages]
 * </pre>
 *
 * Protobuf type {@code tutorial.Emprestimo}
 */
public final class Emprestimo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.Emprestimo)
    EmprestimoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Emprestimo.newBuilder() to construct.
  private Emprestimo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Emprestimo() {
    id_ = "";
    codigo_ = "";
    quantidade_ = "";
    dataReserva_ = "";
    dataEntrega_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Emprestimo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Emprestimo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            codigo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            quantidade_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            dataReserva_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dataEntrega_ = s;
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastUpdated_ != null) {
              subBuilder = lastUpdated_.toBuilder();
            }
            lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastUpdated_);
              lastUpdated_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_Emprestimo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_Emprestimo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.emprestimos.protos.Emprestimo.class, com.emprestimos.protos.Emprestimo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODIGO_FIELD_NUMBER = 2;
  private volatile java.lang.Object codigo_;
  /**
   * <code>string codigo = 2;</code>
   * @return The codigo.
   */
  @java.lang.Override
  public java.lang.String getCodigo() {
    java.lang.Object ref = codigo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codigo_ = s;
      return s;
    }
  }
  /**
   * <code>string codigo = 2;</code>
   * @return The bytes for codigo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodigoBytes() {
    java.lang.Object ref = codigo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codigo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTIDADE_FIELD_NUMBER = 3;
  private volatile java.lang.Object quantidade_;
  /**
   * <code>string quantidade = 3;</code>
   * @return The quantidade.
   */
  @java.lang.Override
  public java.lang.String getQuantidade() {
    java.lang.Object ref = quantidade_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quantidade_ = s;
      return s;
    }
  }
  /**
   * <code>string quantidade = 3;</code>
   * @return The bytes for quantidade.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuantidadeBytes() {
    java.lang.Object ref = quantidade_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quantidade_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATARESERVA_FIELD_NUMBER = 4;
  private volatile java.lang.Object dataReserva_;
  /**
   * <code>string dataReserva = 4;</code>
   * @return The dataReserva.
   */
  @java.lang.Override
  public java.lang.String getDataReserva() {
    java.lang.Object ref = dataReserva_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataReserva_ = s;
      return s;
    }
  }
  /**
   * <code>string dataReserva = 4;</code>
   * @return The bytes for dataReserva.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataReservaBytes() {
    java.lang.Object ref = dataReserva_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataReserva_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAENTREGA_FIELD_NUMBER = 5;
  private volatile java.lang.Object dataEntrega_;
  /**
   * <code>string dataEntrega = 5;</code>
   * @return The dataEntrega.
   */
  @java.lang.Override
  public java.lang.String getDataEntrega() {
    java.lang.Object ref = dataEntrega_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataEntrega_ = s;
      return s;
    }
  }
  /**
   * <code>string dataEntrega = 5;</code>
   * @return The bytes for dataEntrega.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataEntregaBytes() {
    java.lang.Object ref = dataEntrega_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataEntrega_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp lastUpdated_;
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return Whether the lastUpdated field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdated() {
    return lastUpdated_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return The lastUpdated.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdated() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return getLastUpdated();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codigo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quantidade_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, quantidade_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataReserva_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataReserva_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataEntrega_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataEntrega_);
    }
    if (lastUpdated_ != null) {
      output.writeMessage(6, getLastUpdated());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codigo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quantidade_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, quantidade_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataReserva_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataReserva_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataEntrega_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataEntrega_);
    }
    if (lastUpdated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLastUpdated());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.emprestimos.protos.Emprestimo)) {
      return super.equals(obj);
    }
    com.emprestimos.protos.Emprestimo other = (com.emprestimos.protos.Emprestimo) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getCodigo()
        .equals(other.getCodigo())) return false;
    if (!getQuantidade()
        .equals(other.getQuantidade())) return false;
    if (!getDataReserva()
        .equals(other.getDataReserva())) return false;
    if (!getDataEntrega()
        .equals(other.getDataEntrega())) return false;
    if (hasLastUpdated() != other.hasLastUpdated()) return false;
    if (hasLastUpdated()) {
      if (!getLastUpdated()
          .equals(other.getLastUpdated())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CODIGO_FIELD_NUMBER;
    hash = (53 * hash) + getCodigo().hashCode();
    hash = (37 * hash) + QUANTIDADE_FIELD_NUMBER;
    hash = (53 * hash) + getQuantidade().hashCode();
    hash = (37 * hash) + DATARESERVA_FIELD_NUMBER;
    hash = (53 * hash) + getDataReserva().hashCode();
    hash = (37 * hash) + DATAENTREGA_FIELD_NUMBER;
    hash = (53 * hash) + getDataEntrega().hashCode();
    if (hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.emprestimos.protos.Emprestimo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emprestimos.protos.Emprestimo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.emprestimos.protos.Emprestimo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.emprestimos.protos.Emprestimo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.emprestimos.protos.Emprestimo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code tutorial.Emprestimo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.Emprestimo)
      com.emprestimos.protos.EmprestimoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_Emprestimo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_Emprestimo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.emprestimos.protos.Emprestimo.class, com.emprestimos.protos.Emprestimo.Builder.class);
    }

    // Construct using com.emprestimos.protos.Emprestimo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      codigo_ = "";

      quantidade_ = "";

      dataReserva_ = "";

      dataEntrega_ = "";

      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.emprestimos.protos.AddressEmprestimosProtos.internal_static_tutorial_Emprestimo_descriptor;
    }

    @java.lang.Override
    public com.emprestimos.protos.Emprestimo getDefaultInstanceForType() {
      return com.emprestimos.protos.Emprestimo.getDefaultInstance();
    }

    @java.lang.Override
    public com.emprestimos.protos.Emprestimo build() {
      com.emprestimos.protos.Emprestimo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.emprestimos.protos.Emprestimo buildPartial() {
      com.emprestimos.protos.Emprestimo result = new com.emprestimos.protos.Emprestimo(this);
      result.id_ = id_;
      result.codigo_ = codigo_;
      result.quantidade_ = quantidade_;
      result.dataReserva_ = dataReserva_;
      result.dataEntrega_ = dataEntrega_;
      if (lastUpdatedBuilder_ == null) {
        result.lastUpdated_ = lastUpdated_;
      } else {
        result.lastUpdated_ = lastUpdatedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.emprestimos.protos.Emprestimo) {
        return mergeFrom((com.emprestimos.protos.Emprestimo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.emprestimos.protos.Emprestimo other) {
      if (other == com.emprestimos.protos.Emprestimo.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCodigo().isEmpty()) {
        codigo_ = other.codigo_;
        onChanged();
      }
      if (!other.getQuantidade().isEmpty()) {
        quantidade_ = other.quantidade_;
        onChanged();
      }
      if (!other.getDataReserva().isEmpty()) {
        dataReserva_ = other.dataReserva_;
        onChanged();
      }
      if (!other.getDataEntrega().isEmpty()) {
        dataEntrega_ = other.dataEntrega_;
        onChanged();
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.emprestimos.protos.Emprestimo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.emprestimos.protos.Emprestimo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object codigo_ = "";
    /**
     * <code>string codigo = 2;</code>
     * @return The codigo.
     */
    public java.lang.String getCodigo() {
      java.lang.Object ref = codigo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codigo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codigo = 2;</code>
     * @return The bytes for codigo.
     */
    public com.google.protobuf.ByteString
        getCodigoBytes() {
      java.lang.Object ref = codigo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codigo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codigo = 2;</code>
     * @param value The codigo to set.
     * @return This builder for chaining.
     */
    public Builder setCodigo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codigo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codigo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodigo() {
      
      codigo_ = getDefaultInstance().getCodigo();
      onChanged();
      return this;
    }
    /**
     * <code>string codigo = 2;</code>
     * @param value The bytes for codigo to set.
     * @return This builder for chaining.
     */
    public Builder setCodigoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codigo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object quantidade_ = "";
    /**
     * <code>string quantidade = 3;</code>
     * @return The quantidade.
     */
    public java.lang.String getQuantidade() {
      java.lang.Object ref = quantidade_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quantidade_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string quantidade = 3;</code>
     * @return The bytes for quantidade.
     */
    public com.google.protobuf.ByteString
        getQuantidadeBytes() {
      java.lang.Object ref = quantidade_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quantidade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string quantidade = 3;</code>
     * @param value The quantidade to set.
     * @return This builder for chaining.
     */
    public Builder setQuantidade(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      quantidade_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string quantidade = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantidade() {
      
      quantidade_ = getDefaultInstance().getQuantidade();
      onChanged();
      return this;
    }
    /**
     * <code>string quantidade = 3;</code>
     * @param value The bytes for quantidade to set.
     * @return This builder for chaining.
     */
    public Builder setQuantidadeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      quantidade_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataReserva_ = "";
    /**
     * <code>string dataReserva = 4;</code>
     * @return The dataReserva.
     */
    public java.lang.String getDataReserva() {
      java.lang.Object ref = dataReserva_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataReserva_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataReserva = 4;</code>
     * @return The bytes for dataReserva.
     */
    public com.google.protobuf.ByteString
        getDataReservaBytes() {
      java.lang.Object ref = dataReserva_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataReserva_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataReserva = 4;</code>
     * @param value The dataReserva to set.
     * @return This builder for chaining.
     */
    public Builder setDataReserva(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataReserva_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataReserva = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataReserva() {
      
      dataReserva_ = getDefaultInstance().getDataReserva();
      onChanged();
      return this;
    }
    /**
     * <code>string dataReserva = 4;</code>
     * @param value The bytes for dataReserva to set.
     * @return This builder for chaining.
     */
    public Builder setDataReservaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataReserva_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataEntrega_ = "";
    /**
     * <code>string dataEntrega = 5;</code>
     * @return The dataEntrega.
     */
    public java.lang.String getDataEntrega() {
      java.lang.Object ref = dataEntrega_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataEntrega_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dataEntrega = 5;</code>
     * @return The bytes for dataEntrega.
     */
    public com.google.protobuf.ByteString
        getDataEntregaBytes() {
      java.lang.Object ref = dataEntrega_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataEntrega_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataEntrega = 5;</code>
     * @param value The dataEntrega to set.
     * @return This builder for chaining.
     */
    public Builder setDataEntrega(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataEntrega_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataEntrega = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataEntrega() {
      
      dataEntrega_ = getDefaultInstance().getDataEntrega();
      onChanged();
      return this;
    }
    /**
     * <code>string dataEntrega = 5;</code>
     * @param value The bytes for dataEntrega to set.
     * @return This builder for chaining.
     */
    public Builder setDataEntregaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataEntrega_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     * @return Whether the lastUpdated field is set.
     */
    public boolean hasLastUpdated() {
      return lastUpdatedBuilder_ != null || lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     * @return The lastUpdated.
     */
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (lastUpdated_ != null) {
          lastUpdated_ =
            com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
        } else {
          lastUpdated_ = value;
        }
        onChanged();
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder clearLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
        onChanged();
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
      
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.Emprestimo)
  }

  // @@protoc_insertion_point(class_scope:tutorial.Emprestimo)
  private static final com.emprestimos.protos.Emprestimo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.emprestimos.protos.Emprestimo();
  }

  public static com.emprestimos.protos.Emprestimo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Emprestimo>
      PARSER = new com.google.protobuf.AbstractParser<Emprestimo>() {
    @java.lang.Override
    public Emprestimo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Emprestimo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Emprestimo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Emprestimo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.emprestimos.protos.Emprestimo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

