// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_usuarios.proto

package com.usuarios.protos;

public interface AddressUsuariosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressUsuarios)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Usuario usuario = 1;</code>
   */
  java.util.List<com.usuarios.protos.Usuario> 
      getUsuarioList();
  /**
   * <code>repeated .tutorial.Usuario usuario = 1;</code>
   */
  com.usuarios.protos.Usuario getUsuario(int index);
  /**
   * <code>repeated .tutorial.Usuario usuario = 1;</code>
   */
  int getUsuarioCount();
  /**
   * <code>repeated .tutorial.Usuario usuario = 1;</code>
   */
  java.util.List<? extends com.usuarios.protos.UsuarioOrBuilder> 
      getUsuarioOrBuilderList();
  /**
   * <code>repeated .tutorial.Usuario usuario = 1;</code>
   */
  com.usuarios.protos.UsuarioOrBuilder getUsuarioOrBuilder(
      int index);
}
