// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_usuarios.proto

package com.usuarios.protos;

public interface UsuarioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Usuario)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 cpf = 4;</code>
   * @return The cpf.
   */
  int getCpf();

  /**
   * <code>repeated .tutorial.Usuario.PhoneNumber phones = 5;</code>
   */
  java.util.List<com.usuarios.protos.Usuario.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .tutorial.Usuario.PhoneNumber phones = 5;</code>
   */
  com.usuarios.protos.Usuario.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .tutorial.Usuario.PhoneNumber phones = 5;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .tutorial.Usuario.PhoneNumber phones = 5;</code>
   */
  java.util.List<? extends com.usuarios.protos.Usuario.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .tutorial.Usuario.PhoneNumber phones = 5;</code>
   */
  com.usuarios.protos.Usuario.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
