// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Livros.proto

package com.livros.protos;

public interface AddressLivrosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressLivros)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Livro livro = 1;</code>
   */
  java.util.List<com.livros.protos.Livro> 
      getLivroList();
  /**
   * <code>repeated .tutorial.Livro livro = 1;</code>
   */
  com.livros.protos.Livro getLivro(int index);
  /**
   * <code>repeated .tutorial.Livro livro = 1;</code>
   */
  int getLivroCount();
  /**
   * <code>repeated .tutorial.Livro livro = 1;</code>
   */
  java.util.List<? extends com.livros.protos.LivroOrBuilder> 
      getLivroOrBuilderList();
  /**
   * <code>repeated .tutorial.Livro livro = 1;</code>
   */
  com.livros.protos.LivroOrBuilder getLivroOrBuilder(
      int index);
}
