// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Livros.proto

package com.livros.protos;

/**
 * <pre>
 * [START messages]
 * </pre>
 *
 * Protobuf type {@code tutorial.Livro}
 */
public final class Livro extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.Livro)
    LivroOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Livro.newBuilder() to construct.
  private Livro(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Livro() {
    titulo_ = "";
    codigo_ = "";
    qtd_ = "";
    autor_ = "";
    genero_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Livro();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Livro(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            titulo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            codigo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            qtd_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            autor_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            genero_ = s;
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastUpdated_ != null) {
              subBuilder = lastUpdated_.toBuilder();
            }
            lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastUpdated_);
              lastUpdated_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.livros.protos.AddressLivrosProtos.internal_static_tutorial_Livro_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.livros.protos.AddressLivrosProtos.internal_static_tutorial_Livro_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.livros.protos.Livro.class, com.livros.protos.Livro.Builder.class);
  }

  public static final int TITULO_FIELD_NUMBER = 1;
  private volatile java.lang.Object titulo_;
  /**
   * <code>string titulo = 1;</code>
   * @return The titulo.
   */
  @java.lang.Override
  public java.lang.String getTitulo() {
    java.lang.Object ref = titulo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      titulo_ = s;
      return s;
    }
  }
  /**
   * <code>string titulo = 1;</code>
   * @return The bytes for titulo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTituloBytes() {
    java.lang.Object ref = titulo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      titulo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODIGO_FIELD_NUMBER = 2;
  private volatile java.lang.Object codigo_;
  /**
   * <code>string codigo = 2;</code>
   * @return The codigo.
   */
  @java.lang.Override
  public java.lang.String getCodigo() {
    java.lang.Object ref = codigo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codigo_ = s;
      return s;
    }
  }
  /**
   * <code>string codigo = 2;</code>
   * @return The bytes for codigo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodigoBytes() {
    java.lang.Object ref = codigo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codigo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QTD_FIELD_NUMBER = 3;
  private volatile java.lang.Object qtd_;
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string qtd = 3;</code>
   * @return The qtd.
   */
  @java.lang.Override
  public java.lang.String getQtd() {
    java.lang.Object ref = qtd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      qtd_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string qtd = 3;</code>
   * @return The bytes for qtd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQtdBytes() {
    java.lang.Object ref = qtd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      qtd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTOR_FIELD_NUMBER = 4;
  private volatile java.lang.Object autor_;
  /**
   * <code>string autor = 4;</code>
   * @return The autor.
   */
  @java.lang.Override
  public java.lang.String getAutor() {
    java.lang.Object ref = autor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      autor_ = s;
      return s;
    }
  }
  /**
   * <code>string autor = 4;</code>
   * @return The bytes for autor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAutorBytes() {
    java.lang.Object ref = autor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      autor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERO_FIELD_NUMBER = 5;
  private volatile java.lang.Object genero_;
  /**
   * <code>string genero = 5;</code>
   * @return The genero.
   */
  @java.lang.Override
  public java.lang.String getGenero() {
    java.lang.Object ref = genero_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genero_ = s;
      return s;
    }
  }
  /**
   * <code>string genero = 5;</code>
   * @return The bytes for genero.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGeneroBytes() {
    java.lang.Object ref = genero_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genero_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp lastUpdated_;
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return Whether the lastUpdated field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdated() {
    return lastUpdated_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return The lastUpdated.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdated() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return getLastUpdated();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(titulo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, titulo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codigo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(qtd_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, qtd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(autor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, autor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genero_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, genero_);
    }
    if (lastUpdated_ != null) {
      output.writeMessage(6, getLastUpdated());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(titulo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, titulo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codigo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(qtd_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, qtd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(autor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, autor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genero_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, genero_);
    }
    if (lastUpdated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLastUpdated());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.livros.protos.Livro)) {
      return super.equals(obj);
    }
    com.livros.protos.Livro other = (com.livros.protos.Livro) obj;

    if (!getTitulo()
        .equals(other.getTitulo())) return false;
    if (!getCodigo()
        .equals(other.getCodigo())) return false;
    if (!getQtd()
        .equals(other.getQtd())) return false;
    if (!getAutor()
        .equals(other.getAutor())) return false;
    if (!getGenero()
        .equals(other.getGenero())) return false;
    if (hasLastUpdated() != other.hasLastUpdated()) return false;
    if (hasLastUpdated()) {
      if (!getLastUpdated()
          .equals(other.getLastUpdated())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TITULO_FIELD_NUMBER;
    hash = (53 * hash) + getTitulo().hashCode();
    hash = (37 * hash) + CODIGO_FIELD_NUMBER;
    hash = (53 * hash) + getCodigo().hashCode();
    hash = (37 * hash) + QTD_FIELD_NUMBER;
    hash = (53 * hash) + getQtd().hashCode();
    hash = (37 * hash) + AUTOR_FIELD_NUMBER;
    hash = (53 * hash) + getAutor().hashCode();
    hash = (37 * hash) + GENERO_FIELD_NUMBER;
    hash = (53 * hash) + getGenero().hashCode();
    if (hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.livros.protos.Livro parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.livros.protos.Livro parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.livros.protos.Livro parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.livros.protos.Livro parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.livros.protos.Livro parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.livros.protos.Livro parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.livros.protos.Livro parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.livros.protos.Livro parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.livros.protos.Livro parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.livros.protos.Livro parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.livros.protos.Livro parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.livros.protos.Livro parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.livros.protos.Livro prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code tutorial.Livro}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.Livro)
      com.livros.protos.LivroOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.livros.protos.AddressLivrosProtos.internal_static_tutorial_Livro_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.livros.protos.AddressLivrosProtos.internal_static_tutorial_Livro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.livros.protos.Livro.class, com.livros.protos.Livro.Builder.class);
    }

    // Construct using com.livros.protos.Livro.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      titulo_ = "";

      codigo_ = "";

      qtd_ = "";

      autor_ = "";

      genero_ = "";

      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.livros.protos.AddressLivrosProtos.internal_static_tutorial_Livro_descriptor;
    }

    @java.lang.Override
    public com.livros.protos.Livro getDefaultInstanceForType() {
      return com.livros.protos.Livro.getDefaultInstance();
    }

    @java.lang.Override
    public com.livros.protos.Livro build() {
      com.livros.protos.Livro result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.livros.protos.Livro buildPartial() {
      com.livros.protos.Livro result = new com.livros.protos.Livro(this);
      result.titulo_ = titulo_;
      result.codigo_ = codigo_;
      result.qtd_ = qtd_;
      result.autor_ = autor_;
      result.genero_ = genero_;
      if (lastUpdatedBuilder_ == null) {
        result.lastUpdated_ = lastUpdated_;
      } else {
        result.lastUpdated_ = lastUpdatedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.livros.protos.Livro) {
        return mergeFrom((com.livros.protos.Livro)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.livros.protos.Livro other) {
      if (other == com.livros.protos.Livro.getDefaultInstance()) return this;
      if (!other.getTitulo().isEmpty()) {
        titulo_ = other.titulo_;
        onChanged();
      }
      if (!other.getCodigo().isEmpty()) {
        codigo_ = other.codigo_;
        onChanged();
      }
      if (!other.getQtd().isEmpty()) {
        qtd_ = other.qtd_;
        onChanged();
      }
      if (!other.getAutor().isEmpty()) {
        autor_ = other.autor_;
        onChanged();
      }
      if (!other.getGenero().isEmpty()) {
        genero_ = other.genero_;
        onChanged();
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.livros.protos.Livro parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.livros.protos.Livro) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object titulo_ = "";
    /**
     * <code>string titulo = 1;</code>
     * @return The titulo.
     */
    public java.lang.String getTitulo() {
      java.lang.Object ref = titulo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        titulo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string titulo = 1;</code>
     * @return The bytes for titulo.
     */
    public com.google.protobuf.ByteString
        getTituloBytes() {
      java.lang.Object ref = titulo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        titulo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string titulo = 1;</code>
     * @param value The titulo to set.
     * @return This builder for chaining.
     */
    public Builder setTitulo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      titulo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string titulo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitulo() {
      
      titulo_ = getDefaultInstance().getTitulo();
      onChanged();
      return this;
    }
    /**
     * <code>string titulo = 1;</code>
     * @param value The bytes for titulo to set.
     * @return This builder for chaining.
     */
    public Builder setTituloBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      titulo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object codigo_ = "";
    /**
     * <code>string codigo = 2;</code>
     * @return The codigo.
     */
    public java.lang.String getCodigo() {
      java.lang.Object ref = codigo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codigo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codigo = 2;</code>
     * @return The bytes for codigo.
     */
    public com.google.protobuf.ByteString
        getCodigoBytes() {
      java.lang.Object ref = codigo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codigo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codigo = 2;</code>
     * @param value The codigo to set.
     * @return This builder for chaining.
     */
    public Builder setCodigo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codigo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codigo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodigo() {
      
      codigo_ = getDefaultInstance().getCodigo();
      onChanged();
      return this;
    }
    /**
     * <code>string codigo = 2;</code>
     * @param value The bytes for codigo to set.
     * @return This builder for chaining.
     */
    public Builder setCodigoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codigo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object qtd_ = "";
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string qtd = 3;</code>
     * @return The qtd.
     */
    public java.lang.String getQtd() {
      java.lang.Object ref = qtd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        qtd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string qtd = 3;</code>
     * @return The bytes for qtd.
     */
    public com.google.protobuf.ByteString
        getQtdBytes() {
      java.lang.Object ref = qtd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qtd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string qtd = 3;</code>
     * @param value The qtd to set.
     * @return This builder for chaining.
     */
    public Builder setQtd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      qtd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string qtd = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQtd() {
      
      qtd_ = getDefaultInstance().getQtd();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>string qtd = 3;</code>
     * @param value The bytes for qtd to set.
     * @return This builder for chaining.
     */
    public Builder setQtdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      qtd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object autor_ = "";
    /**
     * <code>string autor = 4;</code>
     * @return The autor.
     */
    public java.lang.String getAutor() {
      java.lang.Object ref = autor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        autor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string autor = 4;</code>
     * @return The bytes for autor.
     */
    public com.google.protobuf.ByteString
        getAutorBytes() {
      java.lang.Object ref = autor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        autor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string autor = 4;</code>
     * @param value The autor to set.
     * @return This builder for chaining.
     */
    public Builder setAutor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      autor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string autor = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutor() {
      
      autor_ = getDefaultInstance().getAutor();
      onChanged();
      return this;
    }
    /**
     * <code>string autor = 4;</code>
     * @param value The bytes for autor to set.
     * @return This builder for chaining.
     */
    public Builder setAutorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      autor_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object genero_ = "";
    /**
     * <code>string genero = 5;</code>
     * @return The genero.
     */
    public java.lang.String getGenero() {
      java.lang.Object ref = genero_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genero_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genero = 5;</code>
     * @return The bytes for genero.
     */
    public com.google.protobuf.ByteString
        getGeneroBytes() {
      java.lang.Object ref = genero_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genero_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genero = 5;</code>
     * @param value The genero to set.
     * @return This builder for chaining.
     */
    public Builder setGenero(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      genero_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string genero = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenero() {
      
      genero_ = getDefaultInstance().getGenero();
      onChanged();
      return this;
    }
    /**
     * <code>string genero = 5;</code>
     * @param value The bytes for genero to set.
     * @return This builder for chaining.
     */
    public Builder setGeneroBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      genero_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     * @return Whether the lastUpdated field is set.
     */
    public boolean hasLastUpdated() {
      return lastUpdatedBuilder_ != null || lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     * @return The lastUpdated.
     */
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (lastUpdated_ != null) {
          lastUpdated_ =
            com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
        } else {
          lastUpdated_ = value;
        }
        onChanged();
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public Builder clearLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
        onChanged();
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
      
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.Livro)
  }

  // @@protoc_insertion_point(class_scope:tutorial.Livro)
  private static final com.livros.protos.Livro DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.livros.protos.Livro();
  }

  public static com.livros.protos.Livro getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Livro>
      PARSER = new com.google.protobuf.AbstractParser<Livro>() {
    @java.lang.Override
    public Livro parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Livro(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Livro> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Livro> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.livros.protos.Livro getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

