// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Livros.proto

package com.livros.protos;

public interface LivroOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Livro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string titulo = 1;</code>
   * @return The titulo.
   */
  java.lang.String getTitulo();
  /**
   * <code>string titulo = 1;</code>
   * @return The bytes for titulo.
   */
  com.google.protobuf.ByteString
      getTituloBytes();

  /**
   * <code>string codigo = 2;</code>
   * @return The codigo.
   */
  java.lang.String getCodigo();
  /**
   * <code>string codigo = 2;</code>
   * @return The bytes for codigo.
   */
  com.google.protobuf.ByteString
      getCodigoBytes();

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string qtd = 3;</code>
   * @return The qtd.
   */
  java.lang.String getQtd();
  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>string qtd = 3;</code>
   * @return The bytes for qtd.
   */
  com.google.protobuf.ByteString
      getQtdBytes();

  /**
   * <code>string autor = 4;</code>
   * @return The autor.
   */
  java.lang.String getAutor();
  /**
   * <code>string autor = 4;</code>
   * @return The bytes for autor.
   */
  com.google.protobuf.ByteString
      getAutorBytes();

  /**
   * <code>string genero = 5;</code>
   * @return The genero.
   */
  java.lang.String getGenero();
  /**
   * <code>string genero = 5;</code>
   * @return The bytes for genero.
   */
  com.google.protobuf.ByteString
      getGeneroBytes();

  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
