// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Usuarios.proto

package com.usuarios.protos;

public final class AddressUsuariosProtos {
  private AddressUsuariosProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Usuario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Usuario_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressUsuarios_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_AddressUsuarios_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Usuarios.proto\022\010tutorial\032\037google/proto" +
      "buf/timestamp.proto\"q\n\007Usuario\022\014\n\004nome\030\001" +
      " \001(\t\022\n\n\002id\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\013\n\003cpf\030\004" +
      " \001(\t\0220\n\014last_updated\030\005 \001(\0132\032.google.prot" +
      "obuf.Timestamp\"5\n\017AddressUsuarios\022\"\n\007usu" +
      "ario\030\001 \003(\0132\021.tutorial.UsuarioBf\n\023com.usu" +
      "arios.protosB\025AddressUsuariosProtosP\001Z\013." +
      "./usuarios\252\002(Google.Protobuf.Examples.Ad" +
      "dressUsuariosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_Usuario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Usuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Usuario_descriptor,
        new java.lang.String[] { "Nome", "Id", "Email", "Cpf", "LastUpdated", });
    internal_static_tutorial_AddressUsuarios_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_AddressUsuarios_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_AddressUsuarios_descriptor,
        new java.lang.String[] { "Usuario", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
