// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addresslivros.proto

package com.livros.protos;

public interface LivroOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Livro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 codigo = 1;</code>
   * @return The codigo.
   */
  int getCodigo();

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>int32 qtd = 2;</code>
   * @return The qtd.
   */
  int getQtd();

  /**
   * <code>string autor = 3;</code>
   * @return The autor.
   */
  java.lang.String getAutor();
  /**
   * <code>string autor = 3;</code>
   * @return The bytes for autor.
   */
  com.google.protobuf.ByteString
      getAutorBytes();

  /**
   * <code>string genero = 4;</code>
   * @return The genero.
   */
  java.lang.String getGenero();
  /**
   * <code>string genero = 4;</code>
   * @return The bytes for genero.
   */
  com.google.protobuf.ByteString
      getGeneroBytes();

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
