// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MensagemResponse.proto

package com.mensagem_response.protos;

/**
 * <pre>
 * Our address book file is just one of these.
 * </pre>
 *
 * Protobuf type {@code tutorial.AddressMensagemResponse}
 */
public final class AddressMensagemResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.AddressMensagemResponse)
    AddressMensagemResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddressMensagemResponse.newBuilder() to construct.
  private AddressMensagemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddressMensagemResponse() {
    mensagemresponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddressMensagemResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddressMensagemResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mensagemresponse_ = new java.util.ArrayList<com.mensagem_response.protos.MensagemResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            mensagemresponse_.add(
                input.readMessage(com.mensagem_response.protos.MensagemResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        mensagemresponse_ = java.util.Collections.unmodifiableList(mensagemresponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mensagem_response.protos.AddressMensagemResponseProtos.internal_static_tutorial_AddressMensagemResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mensagem_response.protos.AddressMensagemResponseProtos.internal_static_tutorial_AddressMensagemResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mensagem_response.protos.AddressMensagemResponse.class, com.mensagem_response.protos.AddressMensagemResponse.Builder.class);
  }

  public static final int MENSAGEMRESPONSE_FIELD_NUMBER = 1;
  private java.util.List<com.mensagem_response.protos.MensagemResponse> mensagemresponse_;
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.mensagem_response.protos.MensagemResponse> getMensagemresponseList() {
    return mensagemresponse_;
  }
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mensagem_response.protos.MensagemResponseOrBuilder> 
      getMensagemresponseOrBuilderList() {
    return mensagemresponse_;
  }
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  @java.lang.Override
  public int getMensagemresponseCount() {
    return mensagemresponse_.size();
  }
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  @java.lang.Override
  public com.mensagem_response.protos.MensagemResponse getMensagemresponse(int index) {
    return mensagemresponse_.get(index);
  }
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  @java.lang.Override
  public com.mensagem_response.protos.MensagemResponseOrBuilder getMensagemresponseOrBuilder(
      int index) {
    return mensagemresponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < mensagemresponse_.size(); i++) {
      output.writeMessage(1, mensagemresponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < mensagemresponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, mensagemresponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mensagem_response.protos.AddressMensagemResponse)) {
      return super.equals(obj);
    }
    com.mensagem_response.protos.AddressMensagemResponse other = (com.mensagem_response.protos.AddressMensagemResponse) obj;

    if (!getMensagemresponseList()
        .equals(other.getMensagemresponseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMensagemresponseCount() > 0) {
      hash = (37 * hash) + MENSAGEMRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getMensagemresponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mensagem_response.protos.AddressMensagemResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mensagem_response.protos.AddressMensagemResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Our address book file is just one of these.
   * </pre>
   *
   * Protobuf type {@code tutorial.AddressMensagemResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.AddressMensagemResponse)
      com.mensagem_response.protos.AddressMensagemResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mensagem_response.protos.AddressMensagemResponseProtos.internal_static_tutorial_AddressMensagemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mensagem_response.protos.AddressMensagemResponseProtos.internal_static_tutorial_AddressMensagemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mensagem_response.protos.AddressMensagemResponse.class, com.mensagem_response.protos.AddressMensagemResponse.Builder.class);
    }

    // Construct using com.mensagem_response.protos.AddressMensagemResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMensagemresponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mensagemresponseBuilder_ == null) {
        mensagemresponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        mensagemresponseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mensagem_response.protos.AddressMensagemResponseProtos.internal_static_tutorial_AddressMensagemResponse_descriptor;
    }

    @java.lang.Override
    public com.mensagem_response.protos.AddressMensagemResponse getDefaultInstanceForType() {
      return com.mensagem_response.protos.AddressMensagemResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.mensagem_response.protos.AddressMensagemResponse build() {
      com.mensagem_response.protos.AddressMensagemResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mensagem_response.protos.AddressMensagemResponse buildPartial() {
      com.mensagem_response.protos.AddressMensagemResponse result = new com.mensagem_response.protos.AddressMensagemResponse(this);
      int from_bitField0_ = bitField0_;
      if (mensagemresponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          mensagemresponse_ = java.util.Collections.unmodifiableList(mensagemresponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mensagemresponse_ = mensagemresponse_;
      } else {
        result.mensagemresponse_ = mensagemresponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mensagem_response.protos.AddressMensagemResponse) {
        return mergeFrom((com.mensagem_response.protos.AddressMensagemResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mensagem_response.protos.AddressMensagemResponse other) {
      if (other == com.mensagem_response.protos.AddressMensagemResponse.getDefaultInstance()) return this;
      if (mensagemresponseBuilder_ == null) {
        if (!other.mensagemresponse_.isEmpty()) {
          if (mensagemresponse_.isEmpty()) {
            mensagemresponse_ = other.mensagemresponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMensagemresponseIsMutable();
            mensagemresponse_.addAll(other.mensagemresponse_);
          }
          onChanged();
        }
      } else {
        if (!other.mensagemresponse_.isEmpty()) {
          if (mensagemresponseBuilder_.isEmpty()) {
            mensagemresponseBuilder_.dispose();
            mensagemresponseBuilder_ = null;
            mensagemresponse_ = other.mensagemresponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            mensagemresponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMensagemresponseFieldBuilder() : null;
          } else {
            mensagemresponseBuilder_.addAllMessages(other.mensagemresponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mensagem_response.protos.AddressMensagemResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mensagem_response.protos.AddressMensagemResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.mensagem_response.protos.MensagemResponse> mensagemresponse_ =
      java.util.Collections.emptyList();
    private void ensureMensagemresponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        mensagemresponse_ = new java.util.ArrayList<com.mensagem_response.protos.MensagemResponse>(mensagemresponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mensagem_response.protos.MensagemResponse, com.mensagem_response.protos.MensagemResponse.Builder, com.mensagem_response.protos.MensagemResponseOrBuilder> mensagemresponseBuilder_;

    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public java.util.List<com.mensagem_response.protos.MensagemResponse> getMensagemresponseList() {
      if (mensagemresponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mensagemresponse_);
      } else {
        return mensagemresponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public int getMensagemresponseCount() {
      if (mensagemresponseBuilder_ == null) {
        return mensagemresponse_.size();
      } else {
        return mensagemresponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public com.mensagem_response.protos.MensagemResponse getMensagemresponse(int index) {
      if (mensagemresponseBuilder_ == null) {
        return mensagemresponse_.get(index);
      } else {
        return mensagemresponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder setMensagemresponse(
        int index, com.mensagem_response.protos.MensagemResponse value) {
      if (mensagemresponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMensagemresponseIsMutable();
        mensagemresponse_.set(index, value);
        onChanged();
      } else {
        mensagemresponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder setMensagemresponse(
        int index, com.mensagem_response.protos.MensagemResponse.Builder builderForValue) {
      if (mensagemresponseBuilder_ == null) {
        ensureMensagemresponseIsMutable();
        mensagemresponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        mensagemresponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder addMensagemresponse(com.mensagem_response.protos.MensagemResponse value) {
      if (mensagemresponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMensagemresponseIsMutable();
        mensagemresponse_.add(value);
        onChanged();
      } else {
        mensagemresponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder addMensagemresponse(
        int index, com.mensagem_response.protos.MensagemResponse value) {
      if (mensagemresponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMensagemresponseIsMutable();
        mensagemresponse_.add(index, value);
        onChanged();
      } else {
        mensagemresponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder addMensagemresponse(
        com.mensagem_response.protos.MensagemResponse.Builder builderForValue) {
      if (mensagemresponseBuilder_ == null) {
        ensureMensagemresponseIsMutable();
        mensagemresponse_.add(builderForValue.build());
        onChanged();
      } else {
        mensagemresponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder addMensagemresponse(
        int index, com.mensagem_response.protos.MensagemResponse.Builder builderForValue) {
      if (mensagemresponseBuilder_ == null) {
        ensureMensagemresponseIsMutable();
        mensagemresponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        mensagemresponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder addAllMensagemresponse(
        java.lang.Iterable<? extends com.mensagem_response.protos.MensagemResponse> values) {
      if (mensagemresponseBuilder_ == null) {
        ensureMensagemresponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mensagemresponse_);
        onChanged();
      } else {
        mensagemresponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder clearMensagemresponse() {
      if (mensagemresponseBuilder_ == null) {
        mensagemresponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        mensagemresponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public Builder removeMensagemresponse(int index) {
      if (mensagemresponseBuilder_ == null) {
        ensureMensagemresponseIsMutable();
        mensagemresponse_.remove(index);
        onChanged();
      } else {
        mensagemresponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public com.mensagem_response.protos.MensagemResponse.Builder getMensagemresponseBuilder(
        int index) {
      return getMensagemresponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public com.mensagem_response.protos.MensagemResponseOrBuilder getMensagemresponseOrBuilder(
        int index) {
      if (mensagemresponseBuilder_ == null) {
        return mensagemresponse_.get(index);  } else {
        return mensagemresponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public java.util.List<? extends com.mensagem_response.protos.MensagemResponseOrBuilder> 
         getMensagemresponseOrBuilderList() {
      if (mensagemresponseBuilder_ != null) {
        return mensagemresponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mensagemresponse_);
      }
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public com.mensagem_response.protos.MensagemResponse.Builder addMensagemresponseBuilder() {
      return getMensagemresponseFieldBuilder().addBuilder(
          com.mensagem_response.protos.MensagemResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public com.mensagem_response.protos.MensagemResponse.Builder addMensagemresponseBuilder(
        int index) {
      return getMensagemresponseFieldBuilder().addBuilder(
          index, com.mensagem_response.protos.MensagemResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
     */
    public java.util.List<com.mensagem_response.protos.MensagemResponse.Builder> 
         getMensagemresponseBuilderList() {
      return getMensagemresponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mensagem_response.protos.MensagemResponse, com.mensagem_response.protos.MensagemResponse.Builder, com.mensagem_response.protos.MensagemResponseOrBuilder> 
        getMensagemresponseFieldBuilder() {
      if (mensagemresponseBuilder_ == null) {
        mensagemresponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mensagem_response.protos.MensagemResponse, com.mensagem_response.protos.MensagemResponse.Builder, com.mensagem_response.protos.MensagemResponseOrBuilder>(
                mensagemresponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        mensagemresponse_ = null;
      }
      return mensagemresponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.AddressMensagemResponse)
  }

  // @@protoc_insertion_point(class_scope:tutorial.AddressMensagemResponse)
  private static final com.mensagem_response.protos.AddressMensagemResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mensagem_response.protos.AddressMensagemResponse();
  }

  public static com.mensagem_response.protos.AddressMensagemResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddressMensagemResponse>
      PARSER = new com.google.protobuf.AbstractParser<AddressMensagemResponse>() {
    @java.lang.Override
    public AddressMensagemResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddressMensagemResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddressMensagemResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddressMensagemResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mensagem_response.protos.AddressMensagemResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

