// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MensagemResponse.proto

package com.mensagem_response.protos;

public final class AddressMensagemResponseProtos {
  private AddressMensagemResponseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MensagemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_MensagemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressMensagemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_AddressMensagemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MensagemResponse.proto\022\010tutorial\032\037goog" +
      "le/protobuf/timestamp.proto\"V\n\020MensagemR" +
      "esponse\022\020\n\010mensagem\030\001 \001(\t\0220\n\014last_update" +
      "d\030\005 \001(\0132\032.google.protobuf.Timestamp\"O\n\027A" +
      "ddressMensagemResponse\0224\n\020mensagemrespon" +
      "se\030\001 \003(\0132\032.tutorial.MensagemResponseB\210\001\n" +
      "\034com.mensagem_response.protosB\035AddressMe" +
      "nsagemResponseProtosP\001Z\024../mensagem_resp" +
      "onse\252\0020Google.Protobuf.Examples.AddressM" +
      "ensagemResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_tutorial_MensagemResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_MensagemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_MensagemResponse_descriptor,
        new java.lang.String[] { "Mensagem", "LastUpdated", });
    internal_static_tutorial_AddressMensagemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_AddressMensagemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_AddressMensagemResponse_descriptor,
        new java.lang.String[] { "Mensagemresponse", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
