// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MensagemResponse.proto

package com.mensagem_response.protos;

public interface AddressMensagemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressMensagemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  java.util.List<com.mensagem_response.protos.MensagemResponse> 
      getMensagemresponseList();
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  com.mensagem_response.protos.MensagemResponse getMensagemresponse(int index);
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  int getMensagemresponseCount();
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  java.util.List<? extends com.mensagem_response.protos.MensagemResponseOrBuilder> 
      getMensagemresponseOrBuilderList();
  /**
   * <code>repeated .tutorial.MensagemResponse mensagemresponse = 1;</code>
   */
  com.mensagem_response.protos.MensagemResponseOrBuilder getMensagemresponseOrBuilder(
      int index);
}
