// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MensagemResponse.proto

package com.mensagem_response.protos;

public interface MensagemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.MensagemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagem = 1;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 1;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
